@startuml
class First_Process {
    +start_process()
}

class Second_Process {
+start_process()
}

class Main {
  -List frame
  .
  .
  .

  +Process_Image()
  +Process_Video()
}

class Detect_Robot {
  -List Robot_Pattern_Dict
  -List _Frame_Data


  +detect_robot()
}

class Ui_MainWindow {
  +setupUi()
  +retranslateUi()
}

class Image_Processing {
  -List frameNew
  -List _Frame_Data

  +_start_process()
}

class UDP_Send {
  -List Queue
  .
  .
  .

  +send_data()
}

class HSV_COLOR_PICKER {
  -List frame

  +color_picker()
}

class Capture_Image {
  -List frame

  +load_image()
}

class Capture_Video {
  -List frame

  +start_video_capturing()
  +set_camera_config()
}

class UDP_Connection {
  -Socket socket_ssl

  +__init__()
}

class UDP_Send {
  -QUEUE Sendqueuel

  +run()
  +send()
  +convert_data_to_ProtoBuf_format()
}

class UDP_Receive {
  -QUEUE Sendqueuel

  +run()
  +receive()
  +convert_data_to_ProtoBuf_format()
}

class Client_Socket_ProtoBuf {
  -List ProtoBuf

  +ssl_robot_detection_message()
}

First_Process --*  Main
Second_Process --* UDP_Send
Main *-- Image_Processing : return frame data
Main *-- Detect_Robot : return robots info
Main *-- Ui_MainWindow : Application user interface
Main *-- HSV_COLOR_PICKER : Pick HSV color range
Main *-- Capture_Image : Return frame
Main *-- Capture_Video : Return frame
Main *-- UDP_Send : Send data to server after each process sycle

@enduml