@startuml
class First_Process {
    +start_process()
}

class Second_Process {
+start_process()
}

class Main {
  -List frame
  .
  .
  .

  +Process_Image()
  +Process_Video()
}

class UDP_Send {
  -List Queue
  .
  .
  .

  +send_data()
}
First_Process --|>  Main
Second_Process --|>   UDP_Send
@enduml