// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UDSsockets_SSLClient_ProtoBuf/ssl_client.proto

#include "UDSsockets_SSLClient_ProtoBuf/ssl_client.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace protobuf_UDSsockets_5fSSLClient_5fProtoBuf_2fssl_5fclient_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_UDSsockets_5fSSLClient_5fProtoBuf_2fssl_5fclient_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_SSL_DetectionBall;
extern PROTOBUF_INTERNAL_EXPORT_protobuf_UDSsockets_5fSSLClient_5fProtoBuf_2fssl_5fclient_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_SSL_DetectionRobot;
}  // namespace protobuf_UDSsockets_5fSSLClient_5fProtoBuf_2fssl_5fclient_2eproto
namespace protoblog {
class SSL_DetectionBallDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<SSL_DetectionBall>
      _instance;
} _SSL_DetectionBall_default_instance_;
class SSL_DetectionRobotDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<SSL_DetectionRobot>
      _instance;
} _SSL_DetectionRobot_default_instance_;
class SSL_DetectionFrameDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<SSL_DetectionFrame>
      _instance;
} _SSL_DetectionFrame_default_instance_;
}  // namespace protoblog
namespace protobuf_UDSsockets_5fSSLClient_5fProtoBuf_2fssl_5fclient_2eproto {
static void InitDefaultsSSL_DetectionBall() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::protoblog::_SSL_DetectionBall_default_instance_;
    new (ptr) ::protoblog::SSL_DetectionBall();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::protoblog::SSL_DetectionBall::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_SSL_DetectionBall =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsSSL_DetectionBall}, {}};

static void InitDefaultsSSL_DetectionRobot() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::protoblog::_SSL_DetectionRobot_default_instance_;
    new (ptr) ::protoblog::SSL_DetectionRobot();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::protoblog::SSL_DetectionRobot::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_SSL_DetectionRobot =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsSSL_DetectionRobot}, {}};

static void InitDefaultsSSL_DetectionFrame() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::protoblog::_SSL_DetectionFrame_default_instance_;
    new (ptr) ::protoblog::SSL_DetectionFrame();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::protoblog::SSL_DetectionFrame::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<2> scc_info_SSL_DetectionFrame =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 2, InitDefaultsSSL_DetectionFrame}, {
      &protobuf_UDSsockets_5fSSLClient_5fProtoBuf_2fssl_5fclient_2eproto::scc_info_SSL_DetectionBall.base,
      &protobuf_UDSsockets_5fSSLClient_5fProtoBuf_2fssl_5fclient_2eproto::scc_info_SSL_DetectionRobot.base,}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_SSL_DetectionBall.base);
  ::google::protobuf::internal::InitSCC(&scc_info_SSL_DetectionRobot.base);
  ::google::protobuf::internal::InitSCC(&scc_info_SSL_DetectionFrame.base);
}

::google::protobuf::Metadata file_level_metadata[3];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::protoblog::SSL_DetectionBall, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::protoblog::SSL_DetectionBall, confidence_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::protoblog::SSL_DetectionBall, area_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::protoblog::SSL_DetectionBall, x_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::protoblog::SSL_DetectionBall, y_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::protoblog::SSL_DetectionBall, z_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::protoblog::SSL_DetectionBall, pixel_x_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::protoblog::SSL_DetectionBall, pixel_y_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::protoblog::SSL_DetectionRobot, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::protoblog::SSL_DetectionRobot, confidence_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::protoblog::SSL_DetectionRobot, robot_id_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::protoblog::SSL_DetectionRobot, x_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::protoblog::SSL_DetectionRobot, y_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::protoblog::SSL_DetectionRobot, orientation_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::protoblog::SSL_DetectionRobot, pixel_x_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::protoblog::SSL_DetectionRobot, pixel_y_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::protoblog::SSL_DetectionRobot, height_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::protoblog::SSL_DetectionFrame, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::protoblog::SSL_DetectionFrame, frame_number_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::protoblog::SSL_DetectionFrame, t_capture_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::protoblog::SSL_DetectionFrame, t_sent_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::protoblog::SSL_DetectionFrame, camera_id_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::protoblog::SSL_DetectionFrame, balls_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::protoblog::SSL_DetectionFrame, robots_yellow_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::protoblog::SSL_DetectionFrame, robots_blue_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::protoblog::SSL_DetectionBall)},
  { 12, -1, sizeof(::protoblog::SSL_DetectionRobot)},
  { 25, -1, sizeof(::protoblog::SSL_DetectionFrame)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::protoblog::_SSL_DetectionBall_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::protoblog::_SSL_DetectionRobot_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::protoblog::_SSL_DetectionFrame_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "UDSsockets_SSLClient_ProtoBuf/ssl_client.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 3);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n.UDSsockets_SSLClient_ProtoBuf/ssl_clie"
      "nt.proto\022\tprotoblog\"x\n\021SSL_DetectionBall"
      "\022\022\n\nconfidence\030\001 \001(\002\022\014\n\004area\030\002 \001(\r\022\t\n\001x\030"
      "\003 \001(\002\022\t\n\001y\030\004 \001(\002\022\t\n\001z\030\005 \001(\002\022\017\n\007pixel_x\030\006"
      " \001(\002\022\017\n\007pixel_y\030\007 \001(\002\"\227\001\n\022SSL_DetectionR"
      "obot\022\022\n\nconfidence\030\001 \001(\002\022\020\n\010robot_id\030\002 \001"
      "(\r\022\t\n\001x\030\003 \001(\002\022\t\n\001y\030\004 \001(\002\022\023\n\013orientation\030"
      "\005 \001(\002\022\017\n\007pixel_x\030\006 \001(\002\022\017\n\007pixel_y\030\007 \001(\002\022"
      "\016\n\006height\030\010 \001(\002\"\367\001\n\022SSL_DetectionFrame\022\024"
      "\n\014frame_number\030\001 \001(\r\022\021\n\tt_capture\030\002 \001(\001\022"
      "\016\n\006t_sent\030\003 \001(\001\022\021\n\tcamera_id\030\004 \001(\r\022+\n\005ba"
      "lls\030\005 \003(\0132\034.protoblog.SSL_DetectionBall\022"
      "4\n\rrobots_yellow\030\006 \003(\0132\035.protoblog.SSL_D"
      "etectionRobot\0222\n\013robots_blue\030\007 \003(\0132\035.pro"
      "toblog.SSL_DetectionRobotb\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 593);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "UDSsockets_SSLClient_ProtoBuf/ssl_client.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_UDSsockets_5fSSLClient_5fProtoBuf_2fssl_5fclient_2eproto
namespace protoblog {

// ===================================================================

void SSL_DetectionBall::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int SSL_DetectionBall::kConfidenceFieldNumber;
const int SSL_DetectionBall::kAreaFieldNumber;
const int SSL_DetectionBall::kXFieldNumber;
const int SSL_DetectionBall::kYFieldNumber;
const int SSL_DetectionBall::kZFieldNumber;
const int SSL_DetectionBall::kPixelXFieldNumber;
const int SSL_DetectionBall::kPixelYFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

SSL_DetectionBall::SSL_DetectionBall()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_UDSsockets_5fSSLClient_5fProtoBuf_2fssl_5fclient_2eproto::scc_info_SSL_DetectionBall.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:protoblog.SSL_DetectionBall)
}
SSL_DetectionBall::SSL_DetectionBall(const SSL_DetectionBall& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&confidence_, &from.confidence_,
    static_cast<size_t>(reinterpret_cast<char*>(&pixel_y_) -
    reinterpret_cast<char*>(&confidence_)) + sizeof(pixel_y_));
  // @@protoc_insertion_point(copy_constructor:protoblog.SSL_DetectionBall)
}

void SSL_DetectionBall::SharedCtor() {
  ::memset(&confidence_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&pixel_y_) -
      reinterpret_cast<char*>(&confidence_)) + sizeof(pixel_y_));
}

SSL_DetectionBall::~SSL_DetectionBall() {
  // @@protoc_insertion_point(destructor:protoblog.SSL_DetectionBall)
  SharedDtor();
}

void SSL_DetectionBall::SharedDtor() {
}

void SSL_DetectionBall::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* SSL_DetectionBall::descriptor() {
  ::protobuf_UDSsockets_5fSSLClient_5fProtoBuf_2fssl_5fclient_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_UDSsockets_5fSSLClient_5fProtoBuf_2fssl_5fclient_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const SSL_DetectionBall& SSL_DetectionBall::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_UDSsockets_5fSSLClient_5fProtoBuf_2fssl_5fclient_2eproto::scc_info_SSL_DetectionBall.base);
  return *internal_default_instance();
}


void SSL_DetectionBall::Clear() {
// @@protoc_insertion_point(message_clear_start:protoblog.SSL_DetectionBall)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&confidence_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&pixel_y_) -
      reinterpret_cast<char*>(&confidence_)) + sizeof(pixel_y_));
  _internal_metadata_.Clear();
}

bool SSL_DetectionBall::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:protoblog.SSL_DetectionBall)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // float confidence = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(13u /* 13 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &confidence_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 area = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &area_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // float x = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(29u /* 29 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &x_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // float y = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(37u /* 37 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &y_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // float z = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(45u /* 45 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &z_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // float pixel_x = 6;
      case 6: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(53u /* 53 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &pixel_x_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // float pixel_y = 7;
      case 7: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(61u /* 61 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &pixel_y_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:protoblog.SSL_DetectionBall)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:protoblog.SSL_DetectionBall)
  return false;
#undef DO_
}

void SSL_DetectionBall::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:protoblog.SSL_DetectionBall)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // float confidence = 1;
  if (this->confidence() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(1, this->confidence(), output);
  }

  // uint32 area = 2;
  if (this->area() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(2, this->area(), output);
  }

  // float x = 3;
  if (this->x() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(3, this->x(), output);
  }

  // float y = 4;
  if (this->y() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(4, this->y(), output);
  }

  // float z = 5;
  if (this->z() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(5, this->z(), output);
  }

  // float pixel_x = 6;
  if (this->pixel_x() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(6, this->pixel_x(), output);
  }

  // float pixel_y = 7;
  if (this->pixel_y() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(7, this->pixel_y(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:protoblog.SSL_DetectionBall)
}

::google::protobuf::uint8* SSL_DetectionBall::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:protoblog.SSL_DetectionBall)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // float confidence = 1;
  if (this->confidence() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(1, this->confidence(), target);
  }

  // uint32 area = 2;
  if (this->area() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(2, this->area(), target);
  }

  // float x = 3;
  if (this->x() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(3, this->x(), target);
  }

  // float y = 4;
  if (this->y() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(4, this->y(), target);
  }

  // float z = 5;
  if (this->z() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(5, this->z(), target);
  }

  // float pixel_x = 6;
  if (this->pixel_x() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(6, this->pixel_x(), target);
  }

  // float pixel_y = 7;
  if (this->pixel_y() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(7, this->pixel_y(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:protoblog.SSL_DetectionBall)
  return target;
}

size_t SSL_DetectionBall::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:protoblog.SSL_DetectionBall)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // float confidence = 1;
  if (this->confidence() != 0) {
    total_size += 1 + 4;
  }

  // uint32 area = 2;
  if (this->area() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->area());
  }

  // float x = 3;
  if (this->x() != 0) {
    total_size += 1 + 4;
  }

  // float y = 4;
  if (this->y() != 0) {
    total_size += 1 + 4;
  }

  // float z = 5;
  if (this->z() != 0) {
    total_size += 1 + 4;
  }

  // float pixel_x = 6;
  if (this->pixel_x() != 0) {
    total_size += 1 + 4;
  }

  // float pixel_y = 7;
  if (this->pixel_y() != 0) {
    total_size += 1 + 4;
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void SSL_DetectionBall::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:protoblog.SSL_DetectionBall)
  GOOGLE_DCHECK_NE(&from, this);
  const SSL_DetectionBall* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const SSL_DetectionBall>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:protoblog.SSL_DetectionBall)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:protoblog.SSL_DetectionBall)
    MergeFrom(*source);
  }
}

void SSL_DetectionBall::MergeFrom(const SSL_DetectionBall& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:protoblog.SSL_DetectionBall)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.confidence() != 0) {
    set_confidence(from.confidence());
  }
  if (from.area() != 0) {
    set_area(from.area());
  }
  if (from.x() != 0) {
    set_x(from.x());
  }
  if (from.y() != 0) {
    set_y(from.y());
  }
  if (from.z() != 0) {
    set_z(from.z());
  }
  if (from.pixel_x() != 0) {
    set_pixel_x(from.pixel_x());
  }
  if (from.pixel_y() != 0) {
    set_pixel_y(from.pixel_y());
  }
}

void SSL_DetectionBall::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:protoblog.SSL_DetectionBall)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SSL_DetectionBall::CopyFrom(const SSL_DetectionBall& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:protoblog.SSL_DetectionBall)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SSL_DetectionBall::IsInitialized() const {
  return true;
}

void SSL_DetectionBall::Swap(SSL_DetectionBall* other) {
  if (other == this) return;
  InternalSwap(other);
}
void SSL_DetectionBall::InternalSwap(SSL_DetectionBall* other) {
  using std::swap;
  swap(confidence_, other->confidence_);
  swap(area_, other->area_);
  swap(x_, other->x_);
  swap(y_, other->y_);
  swap(z_, other->z_);
  swap(pixel_x_, other->pixel_x_);
  swap(pixel_y_, other->pixel_y_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata SSL_DetectionBall::GetMetadata() const {
  protobuf_UDSsockets_5fSSLClient_5fProtoBuf_2fssl_5fclient_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_UDSsockets_5fSSLClient_5fProtoBuf_2fssl_5fclient_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void SSL_DetectionRobot::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int SSL_DetectionRobot::kConfidenceFieldNumber;
const int SSL_DetectionRobot::kRobotIdFieldNumber;
const int SSL_DetectionRobot::kXFieldNumber;
const int SSL_DetectionRobot::kYFieldNumber;
const int SSL_DetectionRobot::kOrientationFieldNumber;
const int SSL_DetectionRobot::kPixelXFieldNumber;
const int SSL_DetectionRobot::kPixelYFieldNumber;
const int SSL_DetectionRobot::kHeightFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

SSL_DetectionRobot::SSL_DetectionRobot()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_UDSsockets_5fSSLClient_5fProtoBuf_2fssl_5fclient_2eproto::scc_info_SSL_DetectionRobot.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:protoblog.SSL_DetectionRobot)
}
SSL_DetectionRobot::SSL_DetectionRobot(const SSL_DetectionRobot& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&confidence_, &from.confidence_,
    static_cast<size_t>(reinterpret_cast<char*>(&height_) -
    reinterpret_cast<char*>(&confidence_)) + sizeof(height_));
  // @@protoc_insertion_point(copy_constructor:protoblog.SSL_DetectionRobot)
}

void SSL_DetectionRobot::SharedCtor() {
  ::memset(&confidence_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&height_) -
      reinterpret_cast<char*>(&confidence_)) + sizeof(height_));
}

SSL_DetectionRobot::~SSL_DetectionRobot() {
  // @@protoc_insertion_point(destructor:protoblog.SSL_DetectionRobot)
  SharedDtor();
}

void SSL_DetectionRobot::SharedDtor() {
}

void SSL_DetectionRobot::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* SSL_DetectionRobot::descriptor() {
  ::protobuf_UDSsockets_5fSSLClient_5fProtoBuf_2fssl_5fclient_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_UDSsockets_5fSSLClient_5fProtoBuf_2fssl_5fclient_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const SSL_DetectionRobot& SSL_DetectionRobot::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_UDSsockets_5fSSLClient_5fProtoBuf_2fssl_5fclient_2eproto::scc_info_SSL_DetectionRobot.base);
  return *internal_default_instance();
}


void SSL_DetectionRobot::Clear() {
// @@protoc_insertion_point(message_clear_start:protoblog.SSL_DetectionRobot)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&confidence_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&height_) -
      reinterpret_cast<char*>(&confidence_)) + sizeof(height_));
  _internal_metadata_.Clear();
}

bool SSL_DetectionRobot::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:protoblog.SSL_DetectionRobot)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // float confidence = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(13u /* 13 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &confidence_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 robot_id = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &robot_id_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // float x = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(29u /* 29 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &x_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // float y = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(37u /* 37 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &y_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // float orientation = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(45u /* 45 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &orientation_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // float pixel_x = 6;
      case 6: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(53u /* 53 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &pixel_x_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // float pixel_y = 7;
      case 7: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(61u /* 61 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &pixel_y_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // float height = 8;
      case 8: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(69u /* 69 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &height_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:protoblog.SSL_DetectionRobot)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:protoblog.SSL_DetectionRobot)
  return false;
#undef DO_
}

void SSL_DetectionRobot::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:protoblog.SSL_DetectionRobot)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // float confidence = 1;
  if (this->confidence() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(1, this->confidence(), output);
  }

  // uint32 robot_id = 2;
  if (this->robot_id() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(2, this->robot_id(), output);
  }

  // float x = 3;
  if (this->x() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(3, this->x(), output);
  }

  // float y = 4;
  if (this->y() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(4, this->y(), output);
  }

  // float orientation = 5;
  if (this->orientation() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(5, this->orientation(), output);
  }

  // float pixel_x = 6;
  if (this->pixel_x() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(6, this->pixel_x(), output);
  }

  // float pixel_y = 7;
  if (this->pixel_y() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(7, this->pixel_y(), output);
  }

  // float height = 8;
  if (this->height() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(8, this->height(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:protoblog.SSL_DetectionRobot)
}

::google::protobuf::uint8* SSL_DetectionRobot::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:protoblog.SSL_DetectionRobot)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // float confidence = 1;
  if (this->confidence() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(1, this->confidence(), target);
  }

  // uint32 robot_id = 2;
  if (this->robot_id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(2, this->robot_id(), target);
  }

  // float x = 3;
  if (this->x() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(3, this->x(), target);
  }

  // float y = 4;
  if (this->y() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(4, this->y(), target);
  }

  // float orientation = 5;
  if (this->orientation() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(5, this->orientation(), target);
  }

  // float pixel_x = 6;
  if (this->pixel_x() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(6, this->pixel_x(), target);
  }

  // float pixel_y = 7;
  if (this->pixel_y() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(7, this->pixel_y(), target);
  }

  // float height = 8;
  if (this->height() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(8, this->height(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:protoblog.SSL_DetectionRobot)
  return target;
}

size_t SSL_DetectionRobot::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:protoblog.SSL_DetectionRobot)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // float confidence = 1;
  if (this->confidence() != 0) {
    total_size += 1 + 4;
  }

  // uint32 robot_id = 2;
  if (this->robot_id() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->robot_id());
  }

  // float x = 3;
  if (this->x() != 0) {
    total_size += 1 + 4;
  }

  // float y = 4;
  if (this->y() != 0) {
    total_size += 1 + 4;
  }

  // float orientation = 5;
  if (this->orientation() != 0) {
    total_size += 1 + 4;
  }

  // float pixel_x = 6;
  if (this->pixel_x() != 0) {
    total_size += 1 + 4;
  }

  // float pixel_y = 7;
  if (this->pixel_y() != 0) {
    total_size += 1 + 4;
  }

  // float height = 8;
  if (this->height() != 0) {
    total_size += 1 + 4;
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void SSL_DetectionRobot::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:protoblog.SSL_DetectionRobot)
  GOOGLE_DCHECK_NE(&from, this);
  const SSL_DetectionRobot* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const SSL_DetectionRobot>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:protoblog.SSL_DetectionRobot)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:protoblog.SSL_DetectionRobot)
    MergeFrom(*source);
  }
}

void SSL_DetectionRobot::MergeFrom(const SSL_DetectionRobot& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:protoblog.SSL_DetectionRobot)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.confidence() != 0) {
    set_confidence(from.confidence());
  }
  if (from.robot_id() != 0) {
    set_robot_id(from.robot_id());
  }
  if (from.x() != 0) {
    set_x(from.x());
  }
  if (from.y() != 0) {
    set_y(from.y());
  }
  if (from.orientation() != 0) {
    set_orientation(from.orientation());
  }
  if (from.pixel_x() != 0) {
    set_pixel_x(from.pixel_x());
  }
  if (from.pixel_y() != 0) {
    set_pixel_y(from.pixel_y());
  }
  if (from.height() != 0) {
    set_height(from.height());
  }
}

void SSL_DetectionRobot::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:protoblog.SSL_DetectionRobot)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SSL_DetectionRobot::CopyFrom(const SSL_DetectionRobot& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:protoblog.SSL_DetectionRobot)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SSL_DetectionRobot::IsInitialized() const {
  return true;
}

void SSL_DetectionRobot::Swap(SSL_DetectionRobot* other) {
  if (other == this) return;
  InternalSwap(other);
}
void SSL_DetectionRobot::InternalSwap(SSL_DetectionRobot* other) {
  using std::swap;
  swap(confidence_, other->confidence_);
  swap(robot_id_, other->robot_id_);
  swap(x_, other->x_);
  swap(y_, other->y_);
  swap(orientation_, other->orientation_);
  swap(pixel_x_, other->pixel_x_);
  swap(pixel_y_, other->pixel_y_);
  swap(height_, other->height_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata SSL_DetectionRobot::GetMetadata() const {
  protobuf_UDSsockets_5fSSLClient_5fProtoBuf_2fssl_5fclient_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_UDSsockets_5fSSLClient_5fProtoBuf_2fssl_5fclient_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void SSL_DetectionFrame::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int SSL_DetectionFrame::kFrameNumberFieldNumber;
const int SSL_DetectionFrame::kTCaptureFieldNumber;
const int SSL_DetectionFrame::kTSentFieldNumber;
const int SSL_DetectionFrame::kCameraIdFieldNumber;
const int SSL_DetectionFrame::kBallsFieldNumber;
const int SSL_DetectionFrame::kRobotsYellowFieldNumber;
const int SSL_DetectionFrame::kRobotsBlueFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

SSL_DetectionFrame::SSL_DetectionFrame()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_UDSsockets_5fSSLClient_5fProtoBuf_2fssl_5fclient_2eproto::scc_info_SSL_DetectionFrame.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:protoblog.SSL_DetectionFrame)
}
SSL_DetectionFrame::SSL_DetectionFrame(const SSL_DetectionFrame& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      balls_(from.balls_),
      robots_yellow_(from.robots_yellow_),
      robots_blue_(from.robots_blue_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&t_capture_, &from.t_capture_,
    static_cast<size_t>(reinterpret_cast<char*>(&t_sent_) -
    reinterpret_cast<char*>(&t_capture_)) + sizeof(t_sent_));
  // @@protoc_insertion_point(copy_constructor:protoblog.SSL_DetectionFrame)
}

void SSL_DetectionFrame::SharedCtor() {
  ::memset(&t_capture_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&t_sent_) -
      reinterpret_cast<char*>(&t_capture_)) + sizeof(t_sent_));
}

SSL_DetectionFrame::~SSL_DetectionFrame() {
  // @@protoc_insertion_point(destructor:protoblog.SSL_DetectionFrame)
  SharedDtor();
}

void SSL_DetectionFrame::SharedDtor() {
}

void SSL_DetectionFrame::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* SSL_DetectionFrame::descriptor() {
  ::protobuf_UDSsockets_5fSSLClient_5fProtoBuf_2fssl_5fclient_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_UDSsockets_5fSSLClient_5fProtoBuf_2fssl_5fclient_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const SSL_DetectionFrame& SSL_DetectionFrame::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_UDSsockets_5fSSLClient_5fProtoBuf_2fssl_5fclient_2eproto::scc_info_SSL_DetectionFrame.base);
  return *internal_default_instance();
}


void SSL_DetectionFrame::Clear() {
// @@protoc_insertion_point(message_clear_start:protoblog.SSL_DetectionFrame)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  balls_.Clear();
  robots_yellow_.Clear();
  robots_blue_.Clear();
  ::memset(&t_capture_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&t_sent_) -
      reinterpret_cast<char*>(&t_capture_)) + sizeof(t_sent_));
  _internal_metadata_.Clear();
}

bool SSL_DetectionFrame::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:protoblog.SSL_DetectionFrame)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // uint32 frame_number = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &frame_number_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // double t_capture = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(17u /* 17 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &t_capture_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // double t_sent = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(25u /* 25 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &t_sent_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 camera_id = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(32u /* 32 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &camera_id_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated .protoblog.SSL_DetectionBall balls = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(42u /* 42 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
                input, add_balls()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated .protoblog.SSL_DetectionRobot robots_yellow = 6;
      case 6: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(50u /* 50 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
                input, add_robots_yellow()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated .protoblog.SSL_DetectionRobot robots_blue = 7;
      case 7: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(58u /* 58 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
                input, add_robots_blue()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:protoblog.SSL_DetectionFrame)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:protoblog.SSL_DetectionFrame)
  return false;
#undef DO_
}

void SSL_DetectionFrame::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:protoblog.SSL_DetectionFrame)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 frame_number = 1;
  if (this->frame_number() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->frame_number(), output);
  }

  // double t_capture = 2;
  if (this->t_capture() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(2, this->t_capture(), output);
  }

  // double t_sent = 3;
  if (this->t_sent() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(3, this->t_sent(), output);
  }

  // uint32 camera_id = 4;
  if (this->camera_id() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(4, this->camera_id(), output);
  }

  // repeated .protoblog.SSL_DetectionBall balls = 5;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->balls_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      5,
      this->balls(static_cast<int>(i)),
      output);
  }

  // repeated .protoblog.SSL_DetectionRobot robots_yellow = 6;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->robots_yellow_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      6,
      this->robots_yellow(static_cast<int>(i)),
      output);
  }

  // repeated .protoblog.SSL_DetectionRobot robots_blue = 7;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->robots_blue_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      7,
      this->robots_blue(static_cast<int>(i)),
      output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:protoblog.SSL_DetectionFrame)
}

::google::protobuf::uint8* SSL_DetectionFrame::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:protoblog.SSL_DetectionFrame)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 frame_number = 1;
  if (this->frame_number() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->frame_number(), target);
  }

  // double t_capture = 2;
  if (this->t_capture() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(2, this->t_capture(), target);
  }

  // double t_sent = 3;
  if (this->t_sent() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(3, this->t_sent(), target);
  }

  // uint32 camera_id = 4;
  if (this->camera_id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(4, this->camera_id(), target);
  }

  // repeated .protoblog.SSL_DetectionBall balls = 5;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->balls_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        5, this->balls(static_cast<int>(i)), deterministic, target);
  }

  // repeated .protoblog.SSL_DetectionRobot robots_yellow = 6;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->robots_yellow_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        6, this->robots_yellow(static_cast<int>(i)), deterministic, target);
  }

  // repeated .protoblog.SSL_DetectionRobot robots_blue = 7;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->robots_blue_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        7, this->robots_blue(static_cast<int>(i)), deterministic, target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:protoblog.SSL_DetectionFrame)
  return target;
}

size_t SSL_DetectionFrame::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:protoblog.SSL_DetectionFrame)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // repeated .protoblog.SSL_DetectionBall balls = 5;
  {
    unsigned int count = static_cast<unsigned int>(this->balls_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->balls(static_cast<int>(i)));
    }
  }

  // repeated .protoblog.SSL_DetectionRobot robots_yellow = 6;
  {
    unsigned int count = static_cast<unsigned int>(this->robots_yellow_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->robots_yellow(static_cast<int>(i)));
    }
  }

  // repeated .protoblog.SSL_DetectionRobot robots_blue = 7;
  {
    unsigned int count = static_cast<unsigned int>(this->robots_blue_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->robots_blue(static_cast<int>(i)));
    }
  }

  // double t_capture = 2;
  if (this->t_capture() != 0) {
    total_size += 1 + 8;
  }

  // uint32 frame_number = 1;
  if (this->frame_number() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->frame_number());
  }

  // uint32 camera_id = 4;
  if (this->camera_id() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->camera_id());
  }

  // double t_sent = 3;
  if (this->t_sent() != 0) {
    total_size += 1 + 8;
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void SSL_DetectionFrame::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:protoblog.SSL_DetectionFrame)
  GOOGLE_DCHECK_NE(&from, this);
  const SSL_DetectionFrame* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const SSL_DetectionFrame>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:protoblog.SSL_DetectionFrame)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:protoblog.SSL_DetectionFrame)
    MergeFrom(*source);
  }
}

void SSL_DetectionFrame::MergeFrom(const SSL_DetectionFrame& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:protoblog.SSL_DetectionFrame)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  balls_.MergeFrom(from.balls_);
  robots_yellow_.MergeFrom(from.robots_yellow_);
  robots_blue_.MergeFrom(from.robots_blue_);
  if (from.t_capture() != 0) {
    set_t_capture(from.t_capture());
  }
  if (from.frame_number() != 0) {
    set_frame_number(from.frame_number());
  }
  if (from.camera_id() != 0) {
    set_camera_id(from.camera_id());
  }
  if (from.t_sent() != 0) {
    set_t_sent(from.t_sent());
  }
}

void SSL_DetectionFrame::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:protoblog.SSL_DetectionFrame)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SSL_DetectionFrame::CopyFrom(const SSL_DetectionFrame& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:protoblog.SSL_DetectionFrame)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SSL_DetectionFrame::IsInitialized() const {
  return true;
}

void SSL_DetectionFrame::Swap(SSL_DetectionFrame* other) {
  if (other == this) return;
  InternalSwap(other);
}
void SSL_DetectionFrame::InternalSwap(SSL_DetectionFrame* other) {
  using std::swap;
  CastToBase(&balls_)->InternalSwap(CastToBase(&other->balls_));
  CastToBase(&robots_yellow_)->InternalSwap(CastToBase(&other->robots_yellow_));
  CastToBase(&robots_blue_)->InternalSwap(CastToBase(&other->robots_blue_));
  swap(t_capture_, other->t_capture_);
  swap(frame_number_, other->frame_number_);
  swap(camera_id_, other->camera_id_);
  swap(t_sent_, other->t_sent_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata SSL_DetectionFrame::GetMetadata() const {
  protobuf_UDSsockets_5fSSLClient_5fProtoBuf_2fssl_5fclient_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_UDSsockets_5fSSLClient_5fProtoBuf_2fssl_5fclient_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace protoblog
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::protoblog::SSL_DetectionBall* Arena::CreateMaybeMessage< ::protoblog::SSL_DetectionBall >(Arena* arena) {
  return Arena::CreateInternal< ::protoblog::SSL_DetectionBall >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::protoblog::SSL_DetectionRobot* Arena::CreateMaybeMessage< ::protoblog::SSL_DetectionRobot >(Arena* arena) {
  return Arena::CreateInternal< ::protoblog::SSL_DetectionRobot >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::protoblog::SSL_DetectionFrame* Arena::CreateMaybeMessage< ::protoblog::SSL_DetectionFrame >(Arena* arena) {
  return Arena::CreateInternal< ::protoblog::SSL_DetectionFrame >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
